Update iex-vcpkg-msbuild.yaml

diff --git a/.github/workflows/iex-vcpkg-msbuild.yaml b/.github/workflows/iex-vcpkg-msbuild.yaml
--- a/.github/workflows/iex-vcpkg-msbuild.yaml
+++ b/.github/workflows/iex-vcpkg-msbuild.yaml
@@ -16,17 +16,19 @@ jobs:
       - name: Checkout Repository
         uses: actions/checkout@v3
 
-      - name: Find MSBuild Path using vswhere
+      - name: Locate MSBuild Path
         id: msbuild-locate
+        shell: pwsh
         run: |
           $vswherePath = "C:\Program Files (x86)\Microsoft Visual Studio\Installer\vswhere.exe"
           $msbuildPath = & $vswherePath -latest -products * -requires Microsoft.Component.MSBuild -find MSBuild\**\Bin\MSBuild.exe
+
           if (-not $msbuildPath) {
-          Write-Error "MSBuild.exe not found"
-          exit 1
-          } else {
-          Write-Host "MSBuild found at: $msbuildPath"
+              Write-Error "MSBuild.exe not found."
+              exit 1
           }
+          Write-Host "MSBuild found at: $msbuildPath"
+          echo "MSBUILD_PATH=$msbuildPath" >> $GITHUB_ENV
           echo "::set-output name=msbuild-path::$msbuildPath"
 
       - name: Execute PowerShell Command
