Update ubuntu_unified_workflow.yaml
sudo apt-get install -y libwxgtk3.2-dev libwxgtk-media3.2-dev libwxgtk-webview3.2-dev wx-common wx3.2-headers libtiff6 curl git make cmake clang clang-tools libxml2 libxml2-dev nlohmann-json3-dev build-essential || { echo "Error: Failed to install dependencies. Exiting."; exit 1; }

diff --git a/.github/workflows/ubuntu_unified_workflow.yaml b/.github/workflows/ubuntu_unified_workflow.yaml
--- a/.github/workflows/ubuntu_unified_workflow.yaml
+++ b/.github/workflows/ubuntu_unified_workflow.yaml
@@ -28,12 +28,7 @@ jobs:
     - name: Install Dependencies (Ubuntu)
       run: |
         sudo apt-get update
-        # Check and install if packages are not installed
-        for pkg in libwxgtk-media3.0-gtk3-dev libwxgtk-webview3.0-gtk3-dev libwxgtk3.0-gtk3-dev libxml2 libtiff5 libxml2-dev libtiff5-dev clang-tools; do
-          if ! dpkg-query -W -f='${Status}' $pkg | grep "install ok installed"; then
-            sudo apt-get install -y $pkg
-          fi
-        done
+        sudo apt-get install -y libwxgtk3.2-dev libwxgtk-media3.2-dev libwxgtk-webview3.2-dev wx-common wx3.2-headers libtiff6 curl git make cmake clang clang-tools libxml2 libxml2-dev nlohmann-json3-dev build-essential || { echo "Error: Failed to install dependencies. Exiting."; exit 1; }
         
     # Configure the build with CMake (keeping Cmake/ directory)
     - name: Configure the build with CMake
